name: Django CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        shell: powershell
        run: |
          $IMAGE_NAME = "ghcr.io/${{ github.repository }}:latest".ToLower()
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Run Locally
        shell: powershell
        run: |
          $IMAGE_NAME = "ghcr.io/${{ github.repository }}:latest".ToLower()
          docker stop my_django_app 2>$null
          docker rm my_django_app 2>$null
          docker run -d -p 8000:8000 --name my_django_app $IMAGE_NAME






 






























# stages:
#   - test
#   - build
#   - release
# Django Tests:
#   stage: test
#   image: python:latest
#   script:
#     - pip install -r requirements.txt
#     - python manage.py test --noinput
#   tags:
#     - docker

# Docker Build:
#   stage: build
#   image: docker:stable
#   services:
#     - docker:dind
#   script:
#     - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
#     - docker build _t ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} .
#     - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
#   tags:
#     - docker

# Release:
#   stage: release
#   image: docker:stable
#   services:
#     - docker:dind
#   script:
#     - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
#     - docker pull ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
#     - docker tag ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:latest
#     - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_PROJECT_NAME}:latest
#   when: manual
#   tags:
#     - docker
